footer=made for Leisure Block with ❤
3958382=[{"acronym":"NM"}]
# OCNT弃子
4734310=[{"acronym":"NM"}]
# 爆裂串图
4572048=[{"acronym":"NM"}]
# 就难就难
2735647=[{"acronym":"NM"}]
# tech (by td)
4845516=[{"acronym":"NM"}]
# 新的fd
2818329=[{"acronym":"NM"}]
# rhythm (by td)
3802185=[{"acronym":"HD"}]
# aim
4542656=[{"acronym":"HD"}]
# 常规 AR8
2895643=[{"acronym":"HD"}]
# 右手控
4394798=[{"acronym":"HR"}]
# 左手控
3730051=[{"acronym":"HR"}]
# 高速配小圈
4087100=[{"acronym":"HR"}]
# accuracy
4654687=[{"acronym":"DT"}]
# O!PC原题
4133990=[{"acronym":"DT"}]
# 高速切
4560928=[{"acronym":"DT"}]
# 更高速的切
4693101=[{"acronym":"DT"}]
# 继续Ag
4832129=[{"acronym":"FM"}]
# 高速单点
86390=[{"acronym":"FM"}]
# antimod
2024492=[{"acronym":"FM"}]
# 128BPM+AR8.5说是 (by td)
4803203=[{"acronym":"TB"}]
# 这歌也有6位数版本惹
